INSERT INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Name, Description, Icon, SortIndex)
VALUES ('Players:StandardPlayers', 'CIVILIZATION_NORWAY', 'LEADER_HARALD_ALT', 'UNIT_NORWEGIAN_LONGSHIP', 'LOC_UNIT_NORWEGIAN_LONGSHIP_NAME', 'LOC_UNIT_NORWEGIAN_LONGSHIP_DESCRIPTION', 'ICON_UNIT_NORWEGIAN_LONGSHIP', 10),
('Players:Expansion1_Players', 'CIVILIZATION_NORWAY', 'LEADER_HARALD_ALT', 'UNIT_NORWEGIAN_LONGSHIP', 'LOC_UNIT_NORWEGIAN_LONGSHIP_NAME', 'LOC_UNIT_NORWEGIAN_LONGSHIP_DESCRIPTION', 'ICON_UNIT_NORWEGIAN_LONGSHIP', 10),
('Players:Expansion2_Players', 'CIVILIZATION_NORWAY', 'LEADER_HARALD_ALT', 'UNIT_NORWEGIAN_LONGSHIP', 'LOC_UNIT_NORWEGIAN_LONGSHIP_NAME', 'LOC_UNIT_NORWEGIAN_LONGSHIP_DESCRIPTION', 'ICON_UNIT_NORWEGIAN_LONGSHIP', 10);
