INSERT INTO LeaderTraits (LeaderType, TraitType)
VALUES ('LEADER_HARALD_ALT', 'TRAIT_LEADER_UNIT_NORWEGIAN_LONGSHIP');

INSERT INTO TraitModifiers (TraitType, ModifierId)
VALUES ('TRAIT_LEADER_HARALD_ALT', 'TRAIT_GRANT_COASTAL_RAID_ABILITY');

